# Generated by Django 4.2.7 on 2025-12-15 17:39

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('difficulty_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='难度分值')),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='变现金额')),
                ('status', models.CharField(choices=[('todo', '未完成'), ('in_progress', '进行中'), ('completed', '完成'), ('postponed', '推迟')], default='todo', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('postponed_at', models.DateTimeField(blank=True, null=True, verbose_name='推迟时间')),
                ('postpone_reason', models.TextField(blank=True, verbose_name='推迟原因')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'tasks',
            },
        ),
    ]
