# Generated by Django 4.2.7 on 2025-12-15 18:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='总分值')),
                ('penalty_coefficient', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=4, verbose_name='惩罚系数')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='计算时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_distribution', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '分值分配',
                'verbose_name_plural': '分值分配',
                'db_table': 'score_distributions',
            },
        ),
        migrations.CreateModel(
            name='ScoreAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='基础分值')),
                ('adjusted_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='调整后分值')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='分配比例')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tasks.scoredistribution', verbose_name='分值分配')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '分值分配明细',
                'verbose_name_plural': '分值分配明细',
                'db_table': 'score_allocations',
                'unique_together': {('distribution', 'user')},
            },
        ),
    ]
