# Generated by Django 4.2.7 on 2025-12-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
