# Generated by Django 4.2.7 on 2025-12-15 17:39

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('hardware', '硬件部门'), ('software', '软件部门'), ('marketing', '市场部门')], max_length=20, verbose_name='部门')),
                ('total_okr_score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='部门OKR总分')),
                ('member_count', models.IntegerField(verbose_name='成员数量')),
                ('avg_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='平均分')),
                ('completed_tasks', models.IntegerField(verbose_name='完成任务数')),
                ('avg_difficulty', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='平均难度')),
            ],
            options={
                'verbose_name': '部门报告',
                'verbose_name_plural': '部门报告',
                'db_table': 'department_reports',
            },
        ),
        migrations.CreateModel(
            name='MonthlyEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(verbose_name='月份')),
                ('culture_understanding_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='企业文化理解分值')),
                ('culture_understanding_text', models.TextField(verbose_name='企业文化理解文字')),
                ('culture_understanding_option', models.CharField(max_length=100, verbose_name='企业文化理解选项')),
                ('team_fit_option', models.CharField(max_length=100, verbose_name='团队契合度选项')),
                ('team_fit_text', models.TextField(verbose_name='团队契合度文字')),
                ('team_fit_ranking', models.JSONField(help_text='存储用户对其他员工的排名列表', verbose_name='团队契合度-其他员工排名')),
                ('monthly_growth_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='本月成长分值')),
                ('monthly_growth_text', models.TextField(verbose_name='本月成长文字')),
                ('monthly_growth_option', models.CharField(max_length=100, verbose_name='本月成长选项')),
                ('biggest_contribution_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='本月最大贡献分值')),
                ('biggest_contribution_text', models.TextField(verbose_name='本月最大贡献文字')),
                ('biggest_contribution_option', models.CharField(max_length=100, verbose_name='本月最大贡献选项')),
                ('admin_final_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='管理员最终评分')),
                ('admin_final_comment', models.TextField(blank=True, verbose_name='管理员最终评价')),
                ('admin_evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='管理员评价时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '月度综合评价',
                'verbose_name_plural': '月度综合评价',
                'db_table': 'monthly_evaluations',
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(unique=True, verbose_name='月份')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '月度报告',
                'verbose_name_plural': '月度报告',
                'db_table': 'monthly_reports',
            },
        ),
        migrations.CreateModel(
            name='PeerEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='评分')),
                ('ranking', models.IntegerField(help_text='评价人给被评价人的排名', verbose_name='排名')),
                ('comment', models.TextField(verbose_name='评价文字')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '他人评价',
                'verbose_name_plural': '他人评价',
                'db_table': 'peer_evaluations',
            },
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(verbose_name='月份')),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='工作小时')),
                ('work_hours_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='工作小时分')),
                ('completion_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='完成任务比例')),
                ('completion_rate_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='完成任务比例分')),
                ('avg_difficulty_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='难度平均分')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变现金额总和')),
                ('revenue_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='变现金额分')),
                ('department_avg_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='部门平均分')),
                ('task_rating_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='任务评分')),
                ('culture_understanding_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='企业文化理解分')),
                ('team_fit_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='团队契合度分')),
                ('monthly_growth_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='本月成长分')),
                ('biggest_contribution_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='本月最大贡献分')),
                ('peer_evaluation_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='他人评价分')),
                ('admin_final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='管理员最终评分')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='最终分值')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='计算时间')),
            ],
            options={
                'verbose_name': '绩效分值',
                'verbose_name_plural': '绩效分值',
                'db_table': 'performance_scores',
            },
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(verbose_name='月份')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='工作小时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工作小时',
                'verbose_name_plural': '工作小时',
                'db_table': 'work_hours',
            },
        ),
    ]
