# Generated by Django 4.2.7 on 2025-12-15 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workhours',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_work_hours', to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AddField(
            model_name='workhours',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='performancescore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_peer_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='评价人'),
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='monthly_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_evaluations', to='reports.monthlyevaluation', verbose_name='月度评价'),
        ),
        migrations.AddField(
            model_name='monthlyevaluation',
            name='admin_evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='评价管理员'),
        ),
        migrations.AddField(
            model_name='monthlyevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='被评价人'),
        ),
        migrations.AddField(
            model_name='departmentreport',
            name='monthly_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_reports', to='reports.monthlyreport', verbose_name='月度报告'),
        ),
        migrations.AlterUniqueTogether(
            name='workhours',
            unique_together={('user', 'month')},
        ),
        migrations.AddIndex(
            model_name='performancescore',
            index=models.Index(fields=['month', 'final_score'], name='performance_month_5d1062_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancescore',
            unique_together={('user', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='peerevaluation',
            unique_together={('monthly_evaluation', 'evaluator')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyevaluation',
            unique_together={('user', 'month')},
        ),
    ]
