# Generated by Django 4.2.7 on 2025-12-15 19:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEvaluationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='修改前评分')),
                ('new_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='修改后评分')),
                ('previous_comment', models.TextField(blank=True, verbose_name='修改前评价')),
                ('new_comment', models.TextField(blank=True, verbose_name='修改后评价')),
                ('action_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_evaluation_history', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('monthly_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_history', to='reports.monthlyevaluation', verbose_name='月度评价')),
            ],
            options={
                'verbose_name': '管理员评价历史',
                'verbose_name_plural': '管理员评价历史',
                'db_table': 'admin_evaluation_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
