# Generated by Django 4.2.7 on 2025-12-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_adminevaluationhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhours',
            options={'ordering': ['-month', 'user__name'], 'verbose_name': '工作小时', 'verbose_name_plural': '工作小时'},
        ),
        migrations.AddField(
            model_name='workhours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
