# Generated by Django 4.2.7 on 2025-12-15 17:39

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('task', '任务评价'), ('monthly', '月度评价')], max_length=10, verbose_name='评价类型')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='评分')),
                ('comment', models.TextField(verbose_name='评论')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('month', models.DateField(blank=True, null=True, verbose_name='月份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'db_table': 'reviews',
            },
        ),
    ]
