# Generated by Django 4.2.7 on 2025-12-15 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='被评价人'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价人'),
        ),
        migrations.AddField(
            model_name='review',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['type', 'task'], name='reviews_type_2a2b03_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['month'], name='reviews_month_88fed1_idx'),
        ),
    ]
